time_zone: America/Bogota

default_config:

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfile/lovelace-digital-clock/digital-clock.js
      type: module

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_datetime: !include inputs/input_datetimes.yaml
input_boolean: !include inputs/input_booleans.yaml
input_number: !include inputs/input_numbers.yaml

sensor:
  - platform: template
    sensors:
      time_am_pm:
        friendly_name: "Hora (AM/PM)"
        value_template: >
          {{ now().strftime('%I:%M:%S %p') }}

